services:
  - type: web
    name: tg-bot-ai-consultant
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
    autoDeploy: true
